//! Stable contract addresses and on-chain ids of the XOXNO Lending deployments.
//!
//! Generated by `scripts/sync_wasm.py` from the rs-lending-xlm deployment configuration at `da15776a3`.
//! Do not edit by hand. Governance can add spokes and hubs later: read
//! `get_spoke` on the controller for the live configuration.

/// XOXNO Lending on Stellar mainnet.
pub mod mainnet {
    /// Governance and timelock contract.
    pub const GOVERNANCE: &str = "CC44PEQW7HSEPKAZ5ZRPH2JS5M5KVJXCUBLJ2ZX4E3WCDKMNFILHC2AD";
    /// Controller: the entry point for every user operation.
    pub const CONTROLLER: &str = "CAUCMIN5KSXEVZ7NMXR3LZATGD5EFIEUI5XWTFLYRO2R5OTXI22WE5JX";
    /// Liquidity pool that holds every market's cash.
    pub const POOL: &str = "CBXRNDQMAJFG4VUKMKFEMFS75UUXE2SPSNV4LEEFCSNBCN66PYRWBKXO";
    /// Position NFT: the token id is the account id; its owner owns the account.
    pub const POSITION_NFT: &str = "CAWCSG77AY2W24QZ6ZXLHZU4UXEFHZBM6EI4A4IF7JB5CTY4XND3TI6C";
    /// On-chain hub ids.
    pub const HUB_IDS: &[u32] = &[1, 2, 3];
    /// On-chain spoke ids with the spoke names from the deployment configuration.
    pub const SPOKES: &[(u32, &str)] = &[
        (1, "Blue Chip"),
        (2, "Etherfuse RWA"),
        (3, "Centrifuge RWA"),
        (4, "Stables & FX"),
        (5, "AMM Collateral"),
        (6, "Ondo RWA"),
        (7, "Commodities"),
        (8, "Aquarius Ecosystem"),
    ];
}

/// XOXNO Lending on Stellar testnet.
pub mod testnet {
    /// Governance and timelock contract.
    pub const GOVERNANCE: &str = "CDS33JDOYH3F3FL4QUQ6DV4WKHML2AKHF4LADTZ57FRUAEBTE7NMY5FQ";
    /// Controller: the entry point for every user operation.
    pub const CONTROLLER: &str = "CCXRWJ6SIU2WPFEGLFGJVITPL57QAYIMIO6OAM2NBGNDQSSCK2FFV3F3";
    /// Liquidity pool that holds every market's cash.
    pub const POOL: &str = "CBSGF6QOQAMPFBEVSYPEQHSZRIHJ6RCGUPCRDMUX36DEKRWFAO2PZB5A";
    /// Position NFT: the token id is the account id; its owner owns the account.
    pub const POSITION_NFT: &str = "CDVN5JU675MEDPVRPCYC45AHFC275UH57WEU5OTFE4WFGZBNN7HTLPSY";
    /// On-chain hub ids.
    pub const HUB_IDS: &[u32] = &[1, 2, 3];
    /// On-chain spoke ids with the spoke names from the deployment configuration.
    pub const SPOKES: &[(u32, &str)] = &[
        (1, "Main (USDC/EURC/XLM/BTC)"),
        (2, "XLM + USDC"),
        (3, "Full (BTC/USDC/XLM/EURC/LP + Dual USDC)"),
        (4, "LP Tokens"),
    ];
}
