// Generated by scripts/gen_clients.py from wasm/controller.wasm. Do not edit.

#[soroban_sdk::contractclient(name = "Client")]
pub trait Controller {
    /// Supplies `assets` as collateral and returns the account id; `account_id = 0`
    /// creates an account in `spoke_id`. Third parties may only top up existing
    /// supply positions; owners and delegates may add assets.
    fn supply(
        env: soroban_sdk::Env,
        caller: soroban_sdk::Address,
        account_id: u64,
        spoke_id: u32,
        assets: soroban_sdk::Vec<(HubAssetKey, i128)>,
    ) -> u64;
    /// Borrows against `account_id`'s collateral, paying `to` or the caller.
    /// Requires owner or delegate authorization and post-borrow solvency.
    fn borrow(
        env: soroban_sdk::Env,
        caller: soroban_sdk::Address,
        account_id: u64,
        borrows: soroban_sdk::Vec<(HubAssetKey, i128)>,
        to: Option<soroban_sdk::Address>,
    );
    /// Withdraws collateral to `to` or the caller and returns actual amounts in
    /// asset units. Zero withdraws an asset's full position. Requires owner or
    /// delegate authorization and post-withdrawal solvency.
    fn withdraw(
        env: soroban_sdk::Env,
        caller: soroban_sdk::Address,
        account_id: u64,
        withdrawals: soroban_sdk::Vec<(HubAssetKey, i128)>,
        to: Option<soroban_sdk::Address>,
    ) -> soroban_sdk::Vec<(HubAssetKey, i128)>;
    /// Repays `account_id`'s debt using measured payments from the caller.
    /// Anyone may repay; excess payments are refunded to the caller.
    fn repay(
        env: soroban_sdk::Env,
        caller: soroban_sdk::Address,
        account_id: u64,
        payments: soroban_sdk::Vec<(HubAssetKey, i128)>,
    );
    /// Repays debt and seizes collateral at a health-factor-based bonus.
    /// Permissionless, including self-liquidation; requires liquidator authorization.
    /// Residual bad debt is socialized only at or below the collateral dust cap.
    ///
    /// `Transfer` pays pool cash and returns `0`. `Credit(id)` moves net supply
    /// shares to a different, authorized Normal-mode account on the same spoke;
    /// `Credit(0)` creates one. Credit mode needs no free collateral liquidity
    /// and returns the receiving account id.
    fn liquidate(
        env: soroban_sdk::Env,
        liquidator: soroban_sdk::Address,
        account_id: u64,
        debt_payments: soroban_sdk::Vec<(HubAssetKey, i128)>,
        seize_mode: SeizeMode,
    ) -> u64;
    /// Socializes insolvent debt into the supply index and removes the account
    /// when remaining collateral is at or below the dust cap. Permissionless;
    /// requires caller authorization.
    fn clean_bad_debt(
        env: soroban_sdk::Env,
        caller: soroban_sdk::Address,
        account_id: u64,
    );
    /// Flash-loans `amount` of `asset` to a deployed Wasm `receiver`, invoking
    /// its callback with `data`. The pool recovers principal plus fee before return.
    /// Permissionless; requires caller authorization.
    fn flash_loan(
        env: soroban_sdk::Env,
        caller: soroban_sdk::Address,
        asset: HubAssetKey,
        amount: i128,
        receiver: soroban_sdk::Address,
        data: soroban_sdk::Bytes,
    );
    /// Mints `amount` of `debt` without a flash fee, forwards measured receipts
    /// and invokes the Wasm receiver's `execute_flash_position` callback.
    /// `collaterals` sets minimum controller-balance increases to deposit;
    /// listed `refund_assets` balance increases return to the caller.
    /// Returns the solvent account's id; `account_id = 0` creates it. An existing
    /// account requires owner or delegate authorization and a matching mode.
    fn flash_position(
        env: soroban_sdk::Env,
        caller: soroban_sdk::Address,
        account_id: u64,
        spoke_id: u32,
        mode: PositionMode,
        debt: HubAssetKey,
        amount: i128,
        receiver: soroban_sdk::Address,
        data: soroban_sdk::Bytes,
        collaterals: soroban_sdk::Vec<(HubAssetKey, i128)>,
        refund_assets: soroban_sdk::Vec<soroban_sdk::Address>,
    ) -> u64;
    /// Borrows `debt_to_flash_loan`, swaps into `collateral` and deposits the
    /// proceeds. An `initial_payment` in collateral joins the deposit; one in debt
    /// joins `swap`; a third asset requires `convert_swap` or reverts with
    /// `ConvertStepsRequired`. Returns the account id; `account_id = 0` creates it.
    /// An existing account requires owner or delegate authorization and a matching mode.
    fn multiply(
        env: soroban_sdk::Env,
        caller: soroban_sdk::Address,
        account_id: u64,
        spoke_id: u32,
        collateral: HubAssetKey,
        debt_to_flash_loan: i128,
        debt: HubAssetKey,
        mode: PositionMode,
        swap: soroban_sdk::Bytes,
        initial_payment: Option<(HubAssetKey, i128)>,
        convert_swap: Option<soroban_sdk::Bytes>,
    ) -> u64;
    /// Borrows `amount` of `new_debt`, converts it to `existing_debt` via `swap`
    /// and repays with the proceeds. Requires owner or delegate authorization.
    fn swap_debt(
        env: soroban_sdk::Env,
        caller: soroban_sdk::Address,
        account_id: u64,
        existing_debt: HubAssetKey,
        amount: i128,
        new_debt: HubAssetKey,
        swap: soroban_sdk::Bytes,
    );
    /// Withdraws `amount` of `current`, converts it to `new` via `swap` and
    /// redeposits the proceeds. Requires owner or delegate authorization.
    fn swap_collateral(
        env: soroban_sdk::Env,
        caller: soroban_sdk::Address,
        account_id: u64,
        current: HubAssetKey,
        amount: i128,
        new: HubAssetKey,
        swap: soroban_sdk::Bytes,
    );
    /// Repays `debt` from `collateral`, netting directly for the same hub asset
    /// (`swap` must be empty) or converting otherwise. `close_position` withdraws
    /// all remaining collateral to the caller, reverting with
    /// `CannotCloseWithRemainingDebt` if any debt remains. Requires owner or
    /// delegate authorization.
    fn repay_debt_with_collateral(
        env: soroban_sdk::Env,
        caller: soroban_sdk::Address,
        account_id: u64,
        collateral: HubAssetKey,
        collateral_amount: i128,
        debt: HubAssetKey,
        swap: soroban_sdk::Bytes,
        close_position: bool,
    );
    /// Migrates the caller's position from an approved `blend_pool`: borrows
    /// `debt_caps`, repays Blend and unused borrowing, then deposits withdrawn
    /// `collateral_assets` and `supply_assets`. Returns the account id;
    /// `account_id = 0` creates it. An existing account requires owner or
    /// delegate authorization.
    fn migrate_from_blend(
        env: soroban_sdk::Env,
        caller: soroban_sdk::Address,
        account_id: u64,
        spoke_id: u32,
        hub_id: u32,
        blend_pool: soroban_sdk::Address,
        collateral_assets: soroban_sdk::Vec<soroban_sdk::Address>,
        supply_assets: soroban_sdk::Vec<soroban_sdk::Address>,
        debt_caps: soroban_sdk::Vec<(soroban_sdk::Address, i128)>,
    ) -> u64;
    /// Accrues pool borrow and supply indexes for `assets`. Permissionless;
    /// requires caller authorization.
    fn update_indexes(
        env: soroban_sdk::Env,
        caller: soroban_sdk::Address,
        assets: soroban_sdk::Vec<HubAssetKey>,
    );
    /// Claims pool revenue and forwards measured receipts to the accumulator.
    /// Returns those amounts in asset units, in input order. Permissionless;
    /// requires caller authorization.
    fn claim_revenue(
        env: soroban_sdk::Env,
        caller: soroban_sdk::Address,
        assets: soroban_sdk::Vec<HubAssetKey>,
    ) -> soroban_sdk::Vec<i128>;
    /// Refreshes supply LTV snapshots. With `has_risks`, also refreshes gated
    /// liquidation parameters and requires a final health factor of at least
    /// 1.05 WAD. Permissionless; requires caller authorization.
    fn update_account_threshold(
        env: soroban_sdk::Env,
        caller: soroban_sdk::Address,
        has_risks: bool,
        account_ids: soroban_sdk::Vec<u64>,
    );
    /// Covers a pool backing shortfall using measured receipts from `payer`.
    /// Refunds excess and returns the amount applied in asset units.
    /// Permissionless; requires payer authorization.
    fn recapitalize(
        env: soroban_sdk::Env,
        payer: soroban_sdk::Address,
        hub_asset: HubAssetKey,
        amount: i128,
    ) -> i128;
    /// Extends account storage TTL. Requires account-owner authorization.
    fn renew_account(
        env: soroban_sdk::Env,
        caller: soroban_sdk::Address,
        account_id: u64,
    );
    /// Grants account access to an active, governance-approved position manager.
    /// Requires account-owner authorization.
    fn add_delegate(
        env: soroban_sdk::Env,
        caller: soroban_sdk::Address,
        account_id: u64,
        delegate: soroban_sdk::Address,
    );
    /// Revokes delegate access. Requires account-owner authorization.
    fn remove_delegate(
        env: soroban_sdk::Env,
        caller: soroban_sdk::Address,
        account_id: u64,
        delegate: soroban_sdk::Address,
    );
    /// Returns whether the account's health factor is below 1.0 WAD.
    fn is_liquidatable(env: soroban_sdk::Env, account_id: u64) -> bool;
    /// Returns liquidation-weighted collateral divided by debt, in WAD;
    /// `i128::MAX` if the account has no debt or does not exist.
    fn get_health_factor(env: soroban_sdk::Env, account_id: u64) -> i128;
    /// Returns total supplied collateral in USD (WAD).
    fn get_total_collateral_usd(env: soroban_sdk::Env, account_id: u64) -> i128;
    /// Returns total borrowed debt in USD (WAD).
    fn get_total_borrow_usd(env: soroban_sdk::Env, account_id: u64) -> i128;
    /// Returns supplied `hub_asset` in asset units, or zero without a position.
    fn get_collateral_amount(
        env: soroban_sdk::Env,
        account_id: u64,
        hub_asset: HubAssetKey,
    ) -> i128;
    /// Returns borrowed `hub_asset` in asset units, or zero without a position.
    fn get_borrow_amount(
        env: soroban_sdk::Env,
        account_id: u64,
        hub_asset: HubAssetKey,
    ) -> i128;
    /// Returns supply and debt positions keyed by hub asset, or empty maps
    /// if the account does not exist.
    fn get_account_positions(
        env: soroban_sdk::Env,
        account_id: u64,
    ) -> (
        soroban_sdk::Map<HubAssetKey, AccountPositionRaw>,
        soroban_sdk::Map<HubAssetKey, DebtPositionRaw>,
    );
    /// Returns `account_id`'s spoke id and position mode.
    fn get_account_attributes(
        env: soroban_sdk::Env,
        account_id: u64,
    ) -> AccountAttributes;
    /// Returns whether the account has stored metadata.
    fn account_exists(env: soroban_sdk::Env, account_id: u64) -> bool;
    /// Estimates gross seizure, protocol fees, refunds, maximum payable debt
    /// in USD (WAD), and bonus (BPS). Seizure and fees use asset units for
    /// `Transfer`, RAY-scaled supply shares for `Credit`.
    fn get_liquidation_estimate(
        env: soroban_sdk::Env,
        account_id: u64,
        debt_payments: soroban_sdk::Vec<(HubAssetKey, i128)>,
        seize_mode: SeizeMode,
    ) -> LiquidationEstimate;
    /// Returns liquidation-threshold-weighted collateral in USD (WAD).
    fn get_liquidation_collateral(env: soroban_sdk::Env, account_id: u64) -> i128;
    /// Returns LTV-weighted collateral in USD (WAD), the borrowing limit.
    fn get_ltv_collateral_usd(env: soroban_sdk::Env, account_id: u64) -> i128;
    /// Returns the deployed liquidity pool address.
    fn get_pool_address(env: soroban_sdk::Env) -> soroban_sdk::Address;
    /// Returns the current supply and borrow indexes (RAY) for `hub_asset`.
    fn get_market_index(env: soroban_sdk::Env, hub_asset: HubAssetKey) -> MarketIndexRaw;
    /// Returns supply/borrow indexes (RAY) and oracle price status for each
    /// hub asset. Reverts above `MAX_VIEW_INPUTS`.
    fn get_market_indexes_detailed(
        env: soroban_sdk::Env,
        hub_assets: soroban_sdk::Vec<HubAssetKey>,
    ) -> soroban_sdk::Vec<MarketIndexView>;
    /// Returns the configuration of spoke `spoke_id`.
    fn get_spoke(env: soroban_sdk::Env, spoke_id: u32) -> SpokeConfig;
    /// Returns the spoke asset's configuration; reverts if it is not listed.
    fn get_spoke_asset(
        env: soroban_sdk::Env,
        spoke_id: u32,
        hub_asset: HubAssetKey,
    ) -> SpokeAssetConfig;
    /// Returns spoke supply and borrow usage, or zeroed usage if unrecorded.
    fn get_spoke_usage(
        env: soroban_sdk::Env,
        spoke_id: u32,
        hub_asset: HubAssetKey,
    ) -> SpokeUsageRaw;
    /// Returns the configured price aggregator contract address.
    fn price_aggregator(env: soroban_sdk::Env) -> soroban_sdk::Address;
    /// Returns the LTV-weighted collateral floor in USD (WAD) for accounts with
    /// debt; borrows, withdrawals and strategies check it. Zero disables it.
    fn get_min_borrow_collateral_usd(env: soroban_sdk::Env) -> i128;
    /// Returns whether `pool` is approved as a Blend migration source.
    fn is_blend_pool_approved(env: soroban_sdk::Env, pool: soroban_sdk::Address) -> bool;
}
