// Generated by scripts/gen_clients.py from wasm/pool.wasm. Do not edit.

#[soroban_sdk::contractclient(name = "Client")]
pub trait PoolReader {
    /// Current utilization ratio for a market (RAY fixed-point raw value).
    ///
    /// Computed from stored indexes without forcing a state write.
    fn get_utilisation(env: soroban_sdk::Env, hub_asset: HubAssetKey) -> i128;
    /// Available cash reserves (asset units) for a market.
    fn get_reserves(env: soroban_sdk::Env, hub_asset: HubAssetKey) -> i128;
    /// Current supplier APR as annual RAY at the stored utilization.
    ///
    /// Divide by `RAY` for a unit fraction (0.05 = 5%). Accrual still compounds
    /// the per-millisecond form of this rate.
    fn get_deposit_rate(env: soroban_sdk::Env, hub_asset: HubAssetKey) -> i128;
    /// Current borrow APR as annual RAY at the stored utilization.
    ///
    /// Divide by `RAY` for a unit fraction (0.05 = 5%). Accrual still compounds
    /// the per-millisecond form of this rate.
    fn get_borrow_rate(env: soroban_sdk::Env, hub_asset: HubAssetKey) -> i128;
    /// Revenue in asset units at the **stored** index; does not accrue first.
    ///
    /// `claim_revenue` syncs before paying `min(cash, revenue)`, so the amount
    /// actually paid can be higher (pending accrual mints more shares) or
    /// lower (the cash cap binds under heavy utilization).
    fn get_revenue(env: soroban_sdk::Env, hub_asset: HubAssetKey) -> i128;
    /// Total supplied underlying in asset units (from scaled supply \xc3\x97 supply index).
    fn get_supplied_amount(env: soroban_sdk::Env, hub_asset: HubAssetKey) -> i128;
    /// Total borrowed underlying in asset units (from scaled debt \xc3\x97 borrow index).
    fn get_borrowed_amount(env: soroban_sdk::Env, hub_asset: HubAssetKey) -> i128;
    /// Milliseconds since the market's last interest accrual timestamp.
    fn get_delta_time(env: soroban_sdk::Env, hub_asset: HubAssetKey) -> u64;
    /// Stored market params and state, without accrual.
    fn get_sync_data(env: soroban_sdk::Env, hub_asset: HubAssetKey) -> PoolSyncData;
    /// Returns each market's indexes accrued to the current ledger time, in
    /// request order, without writing state.
    ///
    /// Runs `simulate_update_indexes` on each market's stored sync data.
    fn get_bulk_indexes(
        env: soroban_sdk::Env,
        hub_assets: soroban_sdk::Vec<HubAssetKey>,
    ) -> soroban_sdk::Vec<MarketIndexRaw>;
}
