// Generated by scripts/gen_clients.py from wasm/position_nft.wasm. Do not edit.

#[soroban_sdk::contractclient(name = "Client")]
pub trait PositionNftReader {
    /// Returns the owner of the token with `token_id`.
    ///
    /// # Arguments
    ///
    /// * `e` - Access to the Soroban environment.
    /// * `token_id` - Token ID as a number.
    ///
    /// # Errors
    ///
    /// * `NonFungibleTokenError::NonExistentToken` - If the token does not
    ///   exist.
    fn owner_of(env: soroban_sdk::Env, token_id: u32) -> soroban_sdk::Address;
    /// Returns the number of tokens owned by `account`.
    ///
    /// # Arguments
    ///
    /// * `e` - Access to the Soroban environment.
    /// * `account` - The address for which the balance is being queried.
    fn balance(env: soroban_sdk::Env, account: soroban_sdk::Address) -> u32;
    /// Returns the `token_id` owned by `owner` at a given `index` in the
    /// owner's local list. Use along with
    /// `crate::non_fungible::NonFungibleToken::balance` to enumerate all of
    /// `owner`'s tokens.
    ///
    /// # Arguments
    ///
    /// * `e` - Access to the Soroban environment.
    /// * `owner` - Account of the token's owner.
    /// * `index` - Index of the token in the owner's local list.
    ///
    /// # Errors
    ///
    /// * `crate::non_fungible::NonFungibleTokenError::TokenNotFoundInOwnerList` - When the token
    ///   ID is not found in the owner's enumeration.
    fn get_owner_token_id(
        env: soroban_sdk::Env,
        owner: soroban_sdk::Address,
        index: u32,
    ) -> u32;
    /// Returns the account approved for the token with `token_id`.
    ///
    /// # Arguments
    ///
    /// * `e` - Access to the Soroban environment.
    /// * `token_id` - Token ID as a number.
    ///
    /// # Errors
    ///
    /// * `NonFungibleTokenError::NonExistentToken` - If the token does not
    ///   exist.
    fn get_approved(
        env: soroban_sdk::Env,
        token_id: u32,
    ) -> Option<soroban_sdk::Address>;
    /// Returns whether the `operator` is allowed to manage all the assets of
    /// `owner`.
    ///
    /// # Arguments
    ///
    /// * `e` - Access to the Soroban environment.
    /// * `owner` - Account of the token's owner.
    /// * `operator` - Account to be checked.
    fn is_approved_for_all(
        env: soroban_sdk::Env,
        owner: soroban_sdk::Address,
        operator: soroban_sdk::Address,
    ) -> bool;
}
