// Generated by scripts/gen_clients.py from wasm/price_aggregator.wasm. Do not edit.

#[soroban_sdk::contractclient(name = "Client")]
pub trait PriceReader {
    /// Resolves and returns the price feed for each of `keys`, panicking if
    /// any key fails to resolve to a usable price.
    fn prices(
        env: soroban_sdk::Env,
        keys: soroban_sdk::Vec<PriceKey>,
    ) -> soroban_sdk::Map<PriceKey, PriceFeedRaw>;
    /// Resolves and returns the `PriceStatus` for each of `keys`, without
    /// panicking on individually unusable prices.
    fn quotes(
        env: soroban_sdk::Env,
        keys: soroban_sdk::Vec<PriceKey>,
    ) -> soroban_sdk::Map<PriceKey, PriceStatus>;
    /// Resolves `key` and returns the min and max of its two leg prices as
    /// `(low, high)`, panicking if resolution fails.
    fn price_spread(env: soroban_sdk::Env, key: PriceKey) -> (i128, i128);
    /// Returns the oracle configuration registered for `key`, if any.
    fn oracle(env: soroban_sdk::Env, key: PriceKey) -> Option<AssetOracle>;
}
