#!/usr/bin/env python3
"""Generate the builder-facing clients from the embedded contract specs.

For each contract, writes crates/xoxno-contract-sdk/src/lending/clients/<name>.rs
with one `#[contractclient(name = "Client")]` trait that holds only the functions
in SURFACE below. Signatures come from `stellar contract info interface --output
rust`, and docs from its JSON output, so both match the embedded WASM exactly.
A listed function that the WASM does not export fails the run.

Usage: gen_clients.py [--check]
  --check   fail if a generated file differs from what is committed
"""
import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CRATE = ROOT / "crates" / "xoxno-contract-sdk"
OUT_DIR = CRATE / "src" / "lending" / "clients"

SURFACE = {
    "controller": [
        "supply", "borrow", "withdraw", "repay", "liquidate", "clean_bad_debt",
        "flash_loan", "flash_position", "multiply", "swap_debt", "swap_collateral",
        "repay_debt_with_collateral", "migrate_from_blend", "update_indexes",
        "claim_revenue", "update_account_threshold", "recapitalize", "renew_account",
        "add_delegate", "remove_delegate", "is_liquidatable", "get_health_factor",
        "get_total_collateral_usd", "get_total_borrow_usd", "get_collateral_amount",
        "get_borrow_amount", "get_account_positions", "get_account_attributes",
        "account_exists", "get_liquidation_estimate", "get_liquidation_collateral",
        "get_ltv_collateral_usd", "get_pool_address", "get_market_index",
        "get_market_indexes_detailed", "get_spoke", "get_spoke_asset",
        "get_spoke_usage", "price_aggregator", "get_min_borrow_collateral_usd",
        "is_blend_pool_approved",
    ],
    "pool": [
        "get_utilisation", "get_reserves", "get_deposit_rate", "get_borrow_rate",
        "get_revenue", "get_supplied_amount", "get_borrowed_amount", "get_delta_time",
        "get_sync_data", "get_bulk_indexes",
    ],
    "position_nft": [
        "owner_of", "balance", "get_owner_token_id", "get_approved",
        "is_approved_for_all",
    ],
    "price_aggregator": ["prices", "quotes", "price_spread", "oracle"],
}

TRAITS = {
    "controller": "Controller",
    "pool": "PoolReader",
    "position_nft": "PositionNftReader",
    "price_aggregator": "PriceReader",
}


def interface(wasm: pathlib.Path, fmt: str) -> str:
    return subprocess.run(
        ["stellar", "contract", "info", "interface", "--wasm", str(wasm), "--output", fmt],
        check=True, capture_output=True, text=True,
    ).stdout


def signatures(rust: str) -> dict:
    """Maps each function name to its signature text inside `pub trait Contract`."""
    body = rust[rust.index("pub trait Contract {"):]
    body = body[: body.index("\n}\n")]
    found = {}
    for match in re.finditer(r"\n    fn (\w+)\((.*?)\)(\s*->\s*[^;]+)?;", body, re.S):
        found[match.group(1)] = match.group(0).strip()
    return found


def docs(spec: list) -> dict:
    """Maps each function name to its doc text, with intra-doc links made plain."""
    found = {}
    for entry in spec:
        if "function_v0" in entry:
            text = entry["function_v0"].get("doc", "").replace("\\n", "\n")
            found[entry["function_v0"]["name"]] = re.sub(r"\[`([^`]+)`\](?!\()", r"`\1`", text)
    return found


def indent_list_continuations(text: str) -> list:
    """Indents the wrapped lines of `*` and `-` list items, as rustdoc requires."""
    out, in_item = [], False
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith(("* ", "- ")):
            in_item = True
            out.append(line)
        elif in_item and stripped and not stripped.startswith("#"):
            out.append("  " + stripped)
        else:
            in_item = False
            out.append(line)
    return out


def render(name: str) -> str:
    wasm = CRATE / "wasm" / f"{name}.wasm"
    sigs = signatures(interface(wasm, "rust"))
    doc = docs(json.loads(interface(wasm, "json")))
    missing = [f for f in SURFACE[name] if f not in sigs]
    if missing:
        sys.exit(f"gen_clients: {name}.wasm does not export {', '.join(missing)}")
    lines = [
        f"// Generated by scripts/gen_clients.py from wasm/{name}.wasm. Do not edit.",
        "",
        '#[soroban_sdk::contractclient(name = "Client")]',
        f"pub trait {TRAITS[name]} {{",
    ]
    for function in SURFACE[name]:
        for line in indent_list_continuations(doc.get(function, "")):
            lines.append(f"    /// {line}".rstrip())
        lines.append("    " + sigs[function])
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    check = "--check" in sys.argv[1:]
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    stale = []
    for name in SURFACE:
        path = OUT_DIR / f"{name}.rs"
        text = render(name)
        if check:
            if not path.is_file() or path.read_text() != text:
                stale.append(path.name)
        else:
            path.write_text(text)
    if stale:
        print(f"gen_clients: out of date: {', '.join(stale)}; run scripts/gen_clients.py", file=sys.stderr)
        return 1
    print(f"gen_clients: {'checked' if check else 'wrote'} {len(SURFACE)} clients")
    return 0


if __name__ == "__main__":
    sys.exit(main())
